name: Keep Alive

on:
  schedule:
    - cron: '0 6 * * *'   # 한국시간 15:00
    - cron: '0 12 * * *'  # 한국시간 21:00
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          echo "$(date)" > keep_alive.txt
          git add keep_alive.txt
          git commit -m "Keep alive: $(date)"
          git push
